### ISSUE TITLE
application.yml h2 설정

### ISSUE THREAD

**Issue by pcochoco** [ITDA-project/server#35]
```
#전체 주석 ctrl + /
spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password:
    url: jdbc:h2:tcp://localhost/~/a #연결주소

  jpa:
    hibernate:
      ddl-auto: create #기존 table 삭제 후 재생성
      #create으로 생성 이후 none으로 변경해 재생성을 막아야함
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true #콘솔에 출력되는 sql 쿼리
        show_sql: true #실행된 sql 쿼리
        default_batch_fetch_size: 100
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
```
