### ISSUE TITLE
ci.yml permission denied

### ISSUE THREAD

**Issue by pcochoco** [ITDA-project/server#44]
### 이슈 내용 ###
ci.yml 환경변수 설정 후 커밋 시 permission denied

### 상세 내용 ### 

![Image](https://github.com/user-attachments/assets/f76a3180-755f-43cb-bdc8-fb22637fbc7f)
/home/runner/work/_temp/dbcff6c2-6f01-47f9-8cfc-cb8bae3ed8f1.sh: line 1: ./gradlew: Permission denied
Error: Process completed with exit code 126.

#### ci.yml 
```

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      DB_URL: ${{ secrets.DB_URL }} #url: ${DB_URL} (application.yml 환경변수)
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SMTP_MAIL: ${{ secrets.SMTP_MAIL }}
      SMTP_PW: ${{secrets.SMTP_PW}}
      CLOUD_ACCESS: ${CLOUD_ACCESS}
      CLOUD_SECRET: ${CLOUD_SECRET}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build #./gradlew test 생략 - build로 자동 실행 

# dependency-graph.yml 분리(생략)
```

### 해결 방안 ###
github actions에서 gradlew 파일 실행 권한이 없음
이에 따라 실행을 못함
따라서 .github/workflows/*.yml 안에 권한 부여 필요
```
- name: Grant execute permission for Gradle wrapper
  run: chmod +x ./gradlew
```
